// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Caupo.Data;

#nullable disable

namespace Caupo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250128164040_NovaBaza")]
    partial class NovaBaza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblRadnici", b =>
                {
                    b.Property<int>("idRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dozvole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idRadnika");

                    b.ToTable("Radnici");
                });
#pragma warning restore 612, 618
        }
    }
}
