// <auto-generated />
using System;
using Caupo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caupo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112152821_AddNoteColumnToTblKuhinjaStavke")]
    partial class AddNoteColumnToTblKuhinjaStavke
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblArtikli", b =>
                {
                    b.Property<int>("IdArtikla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternaSifra")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kategorija")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Normativ")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pozicija")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrikazatiNaDispleju")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slika")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArtikla");

                    b.ToTable("tblArtikli");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblBrojBlokaSank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojBloka")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tblBrojBlokaSank");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblBrojPokretanja", b =>
                {
                    b.Property<int>("BrojPokretanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatumPokretanja")
                        .HasColumnType("TEXT");

                    b.HasKey("BrojPokretanja");

                    b.ToTable("tblBrojPokretanja");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblDobavljaci", b =>
                {
                    b.Property<int>("IdDobavljaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mjesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PocetnoStanje")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZR")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDobavljaca");

                    b.ToTable("tblDobavljaci");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblFaktura", b =>
                {
                    b.Property<int>("IdFakture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Printed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Racuni")
                        .HasColumnType("TEXT");

                    b.Property<int>("Radnik")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFakture");

                    b.ToTable("tblFaktura");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblFakturaStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFakture")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblFakturaStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblFirma", b =>
                {
                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grad")
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivFirme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .HasColumnType("TEXT");

                    b.ToTable("tblFirma");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblJediniceMjere", b =>
                {
                    b.Property<int>("IdJedinice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMjere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdJedinice");

                    b.ToTable("tblJediniceMjere");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKategorije", b =>
                {
                    b.Property<int>("IdKategorije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdKategorije");

                    b.ToTable("tblKategorije");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKnjigaKuhinje", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojFakture")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ostatak")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Primljeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Stanje")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Utroseno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblKnjigaKuhinje");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKnjigaSanka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ostatak")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Primljeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Stanje")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Utroseno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblKnjigaSanka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKuhinja", b =>
                {
                    b.Property<int>("IdKuhinje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivStola")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sto")
                        .HasColumnType("TEXT");

                    b.HasKey("IdKuhinje");

                    b.ToTable("tblKuhinja");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKuhinjaStavke", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKuhinje")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zavrseno")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblKuhinjaStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKupci", b =>
                {
                    b.Property<int>("IdKupca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mjesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .HasColumnType("TEXT");

                    b.HasKey("IdKupca");

                    b.ToTable("tblKupci");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKupciNarudzba", b =>
                {
                    b.Property<int>("IdNarudzbe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakturisano")
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("IdNarudzbe");

                    b.ToTable("tblKupciNarudzba");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblKupciNarudzbeStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdNarudzbe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStavke");

                    b.ToTable("tblKupciNarudzbeStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblNarudzbe", b =>
                {
                    b.Property<int>("IdNarudzbe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konobar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vrijeme")
                        .HasColumnType("TEXT");

                    b.HasKey("IdNarudzbe");

                    b.ToTable("tblNarudzbe");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblNarudzbeStavke", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdNarudzbe")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konobar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Printed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Proizvod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sala")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblNarudzbeStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblNormativ", b =>
                {
                    b.Property<int>("IdStavkeNormativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProizvoda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMjere")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repromaterijal")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavkeNormativa");

                    b.ToTable("tblNormativi");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblNormativPica", b =>
                {
                    b.Property<int>("IdNormativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Normativ")
                        .HasColumnType("TEXT");

                    b.HasKey("IdNormativa");

                    b.ToTable("tblNormativPica");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblOtpis", b =>
                {
                    b.Property<int>("idIdOtpisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojOtpisa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("idIdOtpisa");

                    b.ToTable("tblOtpis");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblOtpisStavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojOtpisa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblOtpisStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblPoreskeStope", b =>
                {
                    b.Property<int>("IdStope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Postotak")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStope");

                    b.ToTable("tblPoreskeStope");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblRacunStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStavke");

                    b.ToTable("tblRacunStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblRacuni", b =>
                {
                    b.Property<int>("BrojRacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFiskalnogRacuna")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakturisan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fiskalizovan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reklamiran")
                        .HasColumnType("TEXT");

                    b.HasKey("BrojRacuna");

                    b.ToTable("tblRacuni");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblRadnici", b =>
                {
                    b.Property<int>("IdRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dozvole")
                        .HasColumnType("TEXT");

                    b.Property<string>("IB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRadnika");

                    b.ToTable("tblRadnici");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblReklamiraniRacun", b =>
                {
                    b.Property<int>("BrojRekRacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFiskalnogRacuna")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fiskalizovan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("BrojRekRacuna");

                    b.ToTable("tblReklamiraniRacuni");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblReklamiraniStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojReklamiranogRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProizvoda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Proizvod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblReklamiraniStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblRepromaterijal", b =>
                {
                    b.Property<int>("IdRepromaterijala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NabavnaCijena")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlanskaCijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repromaterijal")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRepromaterijala");

                    b.ToTable("tblRepromaterijal");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUlaz", b =>
                {
                    b.Property<int>("IdUlaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFakture")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosFakture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUlaza");

                    b.ToTable("tblUlaz");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUlazRepromaterijal", b =>
                {
                    b.Property<int>("IdUlaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFakture")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUlaza");

                    b.ToTable("tblUlazRepromaterijal");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUlazRepromaterijalStavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaSaUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosUPDVa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rabat")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblUlazRepromaterijalStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUlazStavke", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaSaUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosUPDVa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelacijaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rabat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblUlazStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUplateDobavljacima", b =>
                {
                    b.Property<int>("IdUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUplate");

                    b.ToTable("tblUplateDobavljacima");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+TblUplateKupaca", b =>
                {
                    b.Property<int>("IdUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Faktura")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUplate");

                    b.ToTable("tblUplateKupaca");
                });
#pragma warning restore 612, 618
        }
    }
}
