// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Caupo.Data;

#nullable disable

namespace Caupo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblArtikli", b =>
                {
                    b.Property<int>("IdArtikla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternaSifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kategorija")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Normativ")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pozicija")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrikazatiNaDispleju")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArtikla");

                    b.ToTable("tblArtikli");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblBrojBlokaSank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojBloka")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tblBrojBlokaSank");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblBrojPokretanja", b =>
                {
                    b.Property<int>("BrojPokretanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatumPokretanja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BrojPokretanja");

                    b.ToTable("tblBrojPokretanja");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblDobavljaci", b =>
                {
                    b.Property<int>("IdDobavljaca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mjesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PocetnoStanje")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDobavljaca");

                    b.ToTable("tblDobavljaci");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblFaktura", b =>
                {
                    b.Property<int>("IdFakture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Printed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Racuni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Radnik")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFakture");

                    b.ToTable("tblFaktura");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblFakturaStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFakture")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblFakturaStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblFirma", b =>
                {
                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NazivFirme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZiroRacun")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("tblFirma");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblJediniceMjere", b =>
                {
                    b.Property<int>("IdJedinice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMjere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdJedinice");

                    b.ToTable("tblJediniceMjere");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKategorije", b =>
                {
                    b.Property<int>("IdKategorije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdKategorije");

                    b.ToTable("tblKategorije");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKnjigaKuhinje", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ostatak")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Primljeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Stanje")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Utroseno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblKnjigaKuhinje");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKnjigaSanka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ostatak")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Primljeno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Stanje")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Utroseno")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblKnjigaSanka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKuhinja", b =>
                {
                    b.Property<int>("IdKuhinje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdKuhinje");

                    b.ToTable("tblKuhinja");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKuhinjaStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKuhinje")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zavrseno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblKuhinjaStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKupci", b =>
                {
                    b.Property<int>("IdKupca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mjesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("PDV")
                        .HasColumnType("TEXT");

                    b.HasKey("IdKupca");

                    b.ToTable("tblKupci");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKupciNarudzba", b =>
                {
                    b.Property<int>("IdNarudzbe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakturisano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JIB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNarudzbe");

                    b.ToTable("tblKupciNarudzba");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblKupciNarudzbeStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdNarudzbe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStavke");

                    b.ToTable("tblKupciNarudzbeStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblNarudzbe", b =>
                {
                    b.Property<int>("idNarudzbe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Konobar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vrijeme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idNarudzbe");

                    b.ToTable("tblNarudzbe");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblNarudzbeStavke", b =>
                {
                    b.Property<int>("idStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konobar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Printed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Proizvod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("idNarudzbe")
                        .HasColumnType("INTEGER");

                    b.HasKey("idStavke");

                    b.ToTable("tblNarudzbeStavke");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblNormativ", b =>
                {
                    b.Property<int>("IdStavkeNormativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProizvoda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JedinicaMjere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repromaterijal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavkeNormativa");

                    b.ToTable("tblNormativ");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblNormativPica", b =>
                {
                    b.Property<int>("IdNormativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Normativ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNormativa");

                    b.ToTable("tblNormativPica");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblOtpis", b =>
                {
                    b.Property<int>("idIdOtpisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojOtpisa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idIdOtpisa");

                    b.ToTable("tblOtpis");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblOtpisStavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojOtpisa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblOtpisStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblPoreskeStope", b =>
                {
                    b.Property<int>("IdStope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Postotak")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStope");

                    b.ToTable("tblPoreskeStope");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblRacunStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtiklNormativ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("REAL");

                    b.Property<int?>("PoreskaStopa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStavke");

                    b.ToTable("tblRacunStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblRacuni", b =>
                {
                    b.Property<int>("BrojRacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFiskalnogRacuna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fakturisan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fiskalizovan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reklamiran")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BrojRacuna");

                    b.ToTable("tblRacuni");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblRadnici", b =>
                {
                    b.Property<int>("idRadnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dozvole")
                        .HasColumnType("TEXT");

                    b.Property<string>("IB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .HasColumnType("TEXT");

                    b.HasKey("idRadnika");

                    b.ToTable("tblRadnici");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblReklamiraniRacun", b =>
                {
                    b.Property<int>("BrojRekRacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFiskalnogRacuna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fiskalizovan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BrojRekRacuna");

                    b.ToTable("tblReklamiraniRacun");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblReklamiraniStavka", b =>
                {
                    b.Property<int>("IdStavke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojReklamiranogRacuna")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdProizvoda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<int>("Proizvod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStavke");

                    b.ToTable("tblReklamiraniStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblRepromaterijal", b =>
                {
                    b.Property<int>("IdRepromaterijala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NabavnaCijena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlanskaCijena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repromaterijal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Zaliha")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRepromaterijala");

                    b.ToTable("tblRepromaterijal");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUlaz", b =>
                {
                    b.Property<int>("IdUlaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosFakture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUlaza");

                    b.ToTable("tblUlaz");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUlazRepromaterijal", b =>
                {
                    b.Property<int>("IdUlaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locked")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUlaza");

                    b.ToTable("tblUlazRepromaterijal");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUlazRepromaterijalStavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CijenaSaUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosBezUPDV")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IznosUPDVa")
                        .HasColumnType("TEXT");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PoreskaStopa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rabat")
                        .HasColumnType("TEXT");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblUlazRepromaterijalStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUlazStavka", b =>
                {
                    b.Property<int>("RedniBroj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artikl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojUlaza")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CijenaBezUPDV")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CijenaSaUPDV")
                        .HasColumnType("REAL");

                    b.Property<decimal>("IznosBezUPDV")
                        .HasColumnType("REAL");

                    b.Property<decimal>("IznosUPDVa")
                        .HasColumnType("REAL");

                    b.Property<int>("JedinicaMjere")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("REAL");

                    b.Property<int>("NivelacijaID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PoreskaStopa")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Rabat")
                        .HasColumnType("REAL");

                    b.Property<int>("Sifra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VrstaArtikla")
                        .HasColumnType("INTEGER");

                    b.HasKey("RedniBroj");

                    b.ToTable("tblUlazStavka");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUplateDobavljacima", b =>
                {
                    b.Property<int>("IdUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobavljac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUplate");

                    b.ToTable("tblUplateDobavljacima");
                });

            modelBuilder.Entity("Caupo.Data.DatabaseTables+tblUplateKupaca", b =>
                {
                    b.Property<int>("IdUplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Faktura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kupac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radnik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUplate");

                    b.ToTable("tblUplateKupaca");
                });
#pragma warning restore 612, 618
        }
    }
}
